spring:
  application:
    name: configuration-service
  #profiles:
  #  active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/debigonz/configuration-repositoryBEE1
        #native:
        #  search-locations: classpath:/config




server:
  port: 8888
