spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: 961091149268-o5qpf4h4i7490qrpj4h49u41h9s6fgos.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies  
        - id: serie-service-route
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - name: CircuitBreaker
              args:
                name: seriesService
                fallbackUri: forward:/fallback/series      
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog
      default-filters:
        - OIDCTokenRelay            

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue  

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE